import {editionLinks} from './edition-nav.js?v=12.0';
import {scrollMultiplier} from './floe-settings.js';
import {DuetAudio} from './duet-audio.js';
import {DuetHud} from './duet-hud.js';
import {hungerPose} from './scenes-media.js';
import {FloeView} from './floe-view.js?v=12.6';
const {speedValue,delayValue,windowValue,laneForKey}=window.BreathDrift;
const {FloeRun,DEFAULT_WINDOW}=window.BreathFloe;
function tuningControls(prefix){return `<section class="tuning-controls" aria-label="三項遊玩調整">
<div><label for="${prefix}Speed">魚群速度 <output data-value="speed">1.0×</output></label><input id="${prefix}Speed" data-tune="speed" type="range" min="0.1" max="2" step="0.1" value="1" aria-label="魚群速度倍率"><small>0.1× — 2.0× · 只調整魚群前進速度</small></div>
<div><label for="${prefix}Delay">判定延遲 <output data-value="delay">0 ms</output></label><input id="${prefix}Delay" data-tune="delay" type="range" min="-200" max="200" step="5" value="0" aria-label="判定延遲毫秒"><small>−200 — +200 ms · 正值：晚按才正中；負值：提早按</small></div>
<div><label for="${prefix}Window">判定範圍 <output data-value="window">±125 ms</output></label><input id="${prefix}Window" data-tune="window" type="range" min="40" max="200" step="5" value="125" aria-label="判定範圍毫秒"><small>前後各 40 — 200 ms · 數值越小，判定越嚴格</small></div>
<button class="reset-tuning" data-reset-tuning>重設為目前難度預設</button></section>`;}

document.body.innerHTML=`<main class="world" data-scene="start"><canvas id="scene" tabindex="0" aria-label="第十二版冰海新章"></canvas><div class="grain"></div>
<header><a class="brand" href="index.html">≈ Breath <small>一口氣的旅程</small></a><nav aria-label="切換遊戲版本">${editionLinks('floe')}</nav><div class="tools"><button id="sound" aria-label="開啟聲音" aria-pressed="false" title="點一下聽開始介面音樂">♫</button><button id="pause" class="hidden" aria-label="暫停">Ⅱ</button></div></header>
<button class="tuning-dock" id="openTuning" aria-label="開啟三項遊玩調整"><span>遊玩調整 <b>☷</b></span><strong id="tuningSummary">1.0× · 0 ms · ±125 ms</strong><small>魚速 · 判定延遲 · 判定範圍</small></button><div class="scene-number" id="sceneNumber">01 / 冰川上的小海豹</div>
<section id="opening" class="opening ice-menu">
<div class="menu-heading"><span class="eyebrow">12 / 冰海新章</span><h1>BREATH<em>一口氣，游向你。</em></h1><p class="intro">跟著音樂，吃一口小魚。<br>在冰海裡找到自己的節奏。</p></div>
<div class="menu-actions">
<button id="menuStart" class="ice-button start-ice" aria-label="START 選曲開始"><img src="assets/floe/Start-Botton.webp" alt=""><img class="pressed" src="assets/floe/Start-Botton-Click.webp" alt=""></button>
<button id="menuCredits" class="ice-button credits-ice" aria-label="CREDITS 製作團隊"><img src="assets/floe/Credits-Botton.webp" alt=""><img class="pressed" src="assets/floe/Credits-Botton-Click.webp" alt=""></button>
<button id="menuExit" class="ice-button exit-ice" aria-label="EXIT 離開遊戲"><img src="assets/floe/Exit-Botton.webp" alt=""><img class="pressed" src="assets/floe/Exit-Botton-Click.webp" alt=""></button>
</div><div class="menu-track"><p id="menuSong">音樂1</p><p id="difficultyNote"></p><button class="setup-link" id="openSetup">選曲・難度與設定</button><p id="error" class="error" role="alert"></p></div></section>
<button class="home-ice icon-ice" id="home" aria-label="回到主畫面"><img src="assets/floe/Home-Botton.webp" alt=""></button>
<div class="scrim hidden" id="credits"><section class="dialog credits-card" role="dialog" aria-modal="true" aria-labelledby="creditsTitle"><h2 id="creditsTitle">CREDITS</h2><p class="team-name">第二組</p><p>內容待補</p><button id="closeCredits" class="icon-ice back-ice" aria-label="返回主畫面"><img src="assets/floe/Back-Botton.webp" alt=""></button></section></div>
<div class="scrim hidden" id="restScreen"><section class="dialog credits-card" role="dialog" aria-modal="true" aria-labelledby="restTitle"><h2 id="restTitle">先休息一下。</h2><p>音樂已停止，隨時可以回到冰海。</p><button id="closeRest" class="icon-ice back-ice" aria-label="返回遊戲主畫面"><img src="assets/floe/Back-Botton.webp" alt=""></button></section></div>
<div class="scrim hidden" id="setup"><section class="setup-card" role="dialog" aria-modal="true" aria-labelledby="setupTitle"><div class="setup-head"><h2 id="setupTitle">選一首歌，準備出發。</h2><button id="closeSetup" class="icon-ice back-ice" aria-label="關閉設定"><img src="assets/floe/Back-Botton.webp" alt=""></button></div>
<fieldset class="songs song-picker" id="songPicker"><legend>選擇音樂</legend></fieldset><fieldset class="difficulties"><legend>選擇難度</legend><label><input type="radio" name="level" value="beginner"><span><b>新手</b><small>每 4 拍一次</small></span></label><label><input type="radio" name="level" value="intermediate"><span><b>中階</b><small>每 2 拍一次</small></span></label><label><input type="radio" name="level" value="expert" checked><span><b>高手</b><small>全拍＋八分連打</small></span></label></fieldset>
<button class="primary play-song" id="start" disabled>正在準備冰海…</button><label class="practice"><input type="checkbox" id="practice">輕鬆練習<small>不會死亡</small></label><label class="practice"><input type="checkbox" id="blind">純聽練習<small>隱藏魚群，不會死亡</small></label><p class="blind-hint">D／F／↑ 打上排，J／K／↓ 打下排。上岸吸氣時連打補氣，時間到自動下海。空拍可自由上下移動，不扣分、不斷連擊。魚靠近判定點時，太早、太晚或按錯軌會 Miss，該魚不能再補按；漏接也會 Miss。節奏穩定度歸零則旅程結束。魚速可調，歌曲與判定時間不變。</p>${tuningControls("setup")}<details class="settings"><summary>拍點試聽與耳機校正</summary><p>試聽會在實際譜面起音加上輕響。聽到輕響時點「跟拍」，收集 6 次以上再套用。校正含個人反應時間，可手動微調。</p><div class="sync-buttons"><button id="listen">試聽 16 秒</button><button id="calTap">跟拍</button><button id="applyOffset" disabled>套用校正</button></div><p class="sync-status" id="syncStatus">輸出裝置延遲會自動補償；此處調整剩餘誤差。</p></details><div id="artTools" ${new URLSearchParams(location.search).get('dev')==='1'?'':'hidden'}><a class="audit-link" href="beat-recorder.html" target="_blank">手動錄拍工具 ↗</a> · <a class="audit-link" id="timingReport" href="assets/floe/timing-report.json" target="_blank">所選歌曲拍點分析 ↗</a><details class="settings sound-library"><summary>音效試聽 · 團隊素材</summary><p>本版提供「音樂1」、「音樂2」與「音樂3」。魚速與音樂速度獨立；團隊音效會保持輕量，讓鼓點清楚。</p><label for="soundChoice">音效</label><select id="soundChoice"><option value="start">遊戲開始</option><option value="inhale">吸氣</option><option value="breathGood">精準呼吸</option><option value="breathBad">不精準呼吸</option><option value="dive">下水大水花</option><option value="surface">出水</option><option value="eat">吃魚</option><option value="ice">撞到冰</option><option value="fisher">撞倒垂釣者</option><option value="hungry">肚子餓</option><option value="happy">海豹開心／呼喚</option><option value="sad">海豹難過</option><option value="belly">海豹拍肚子</option><option value="ghost">變成餓死鬼</option><option value="angel">變成天使</option><option value="button">按鍵</option></select><button id="previewSound">試聽音效</button><p id="soundStatus" role="status"></p></details><div class="preview-bar"><b>四幕畫面預覽 · 不會開始遊戲</b><button data-preview="start">開始</button><button data-preview="breath">吸氣開始</button><button data-preview="breath-full">吸滿氣</button><button data-preview="dive" data-food="0">海底 · 瘦</button><button data-preview="dive" data-food="120">海底 · 中</button><button data-preview="dive" data-food="240">海底 · 胖</button><button data-preview="friends">朋友</button><button data-preview="rest">攤平</button><button data-preview="hungryGhost">餓死鬼</button><button data-preview="angel">天使</button></div></div></section></div><div class="preview-control hidden" id="previewControl">畫面預覽 · 非實際成績<button id="exitPreview">返回</button></div>
<section id="breathCaption" class="breath-caption hidden"><h2>連打吸氣，準備下海！</h2><p>按越多下補越多氣。SPACE 或上下排按鍵連打，每下補 5% 氧氣，倒數結束自動下海。</p></section>
<section id="hud" class="hud route-hud hidden"><div class="song-info"><small id="chapter"></small><h2 id="trackTitle"></h2><span id="form"></span></div><div class="stats"><div class="stability"><small>節奏穩定 <span id="stabilityValue">100%</span></small><div id="stabilityMeter" role="progressbar" aria-label="節奏穩定度" aria-valuemin="0" aria-valuemax="100"><i id="stabilityFill"></i></div></div><div class="air"><small>肺活量 <span id="airValue"></span></small><div id="airMeter" role="progressbar" aria-label="肺活量" aria-valuemin="0" aria-valuemax="100"><i id="airFill"></i></div></div><div class="food"><small>飽食度 <span id="foodValue"></span></small><div class="food-meter" role="progressbar" id="foodMeter" aria-label="飽食度" aria-valuemin="0" aria-valuemax="360"><i id="foodFill"></i></div><div class="rhythm-labels"><span>120 · 長大</span><span>240 · 進化</span><span>360 · 吃飽</span></div></div></div></section>
<div class="combo-box"><b id="comboValue">0</b><span>COMBO</span></div><div class="score-box">SCORE<b id="scoreValue">0000000</b><small>ACCURACY <strong id="accuracyValue">100.00%</strong></small></div><div class="judgement hidden" id="judgement" aria-live="off"><b id="grade">PERFECT</b><small id="timing">JUST!</small></div><div class="journey-hint hidden" id="hint" aria-live="polite"></div><div class="warning hidden" id="warning" role="status"></div><button class="tap hidden" id="tap">連打補氣<small>SPACE</small></button><div class="lane-buttons hidden" id="laneButtons"><button id="upperTap" aria-label="打上排 D F 或方向上">上排 <b>D F ↑</b></button><button id="lowerTap" aria-label="打下排 J K 或方向下">下排 <b>J K ↓</b></button></div>
<section id="ending" class="end-card hidden" aria-live="polite"><div class="eyebrow" id="endLabel"></div><h2 id="endTitle"></h2><p id="endCopy"></p><button class="primary" id="retry">再一次 ↗</button><button class="text-button" id="back">回到開始</button></section>
<div class="scrim hidden" id="paused"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="pauseTitle"><h2 id="pauseTitle">海會等你。</h2><p id="pauseCopy">氧氣、音樂與旅程都停在這一刻。</p>${tuningControls("pause")}<button class="primary" id="resume">繼續旅行 ↗</button><button class="text-button" id="quit">回到開始</button></section></div>
<footer><span id="footerSong">音樂1 · 438 隻魚</span><span class="key-hint"><kbd>D F ↑</kbd> 上排 <i>·</i> <kbd>J K ↓</kbd> 下排 <i>·</i> ESC 暫停</span><span id="clock">3 分 10 秒</span></footer><div class="timeline"><i id="progress"></i></div></main>`;
const $=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on),view=new FloeView($('scene')),pulseHud=new DuetHud();
let artPreview=null,lastHungerCycle=-1;
let tracks=[],game,audio,offset=0,muted=false,loading=false,breathTime=0,previous=0,visual=0,finished=false,audition=false,samples=[],clicks=[],lastCal=-1;
let scrollSpeed=1,hitWindow=DEFAULT_WINDOW;
try{const saved=JSON.parse(localStorage.getItem('breath-floe-tuning')||'{}');scrollSpeed=speedValue(saved.speed??1);offset=delayValue(saved.delay??0);hitWindow=saved.windowVersion===2?windowValue(saved.window??DEFAULT_WINDOW):DEFAULT_WINDOW;}catch{}
function syncTuning(){
  view.speedMultiplier=scrollMultiplier(scrollSpeed);game?.setTiming(offset,hitWindow);
  const values={speed:scrollSpeed,delay:offset,window:hitWindow},labels={speed:scrollSpeed.toFixed(1)+'×',delay:(offset>0?'+':'')+offset+' ms',window:'±'+hitWindow+' ms'};
  for(const key of Object.keys(values)){document.querySelectorAll(`[data-tune="${key}"]`).forEach(n=>n.value=values[key]);document.querySelectorAll(`[data-value="${key}"]`).forEach(n=>n.textContent=labels[key]);}
  $('tuningSummary').innerHTML=Object.values(labels).map(label=>`<span>${label.replace(' ms','ms')}</span>`).join('');
  try{localStorage.setItem('breath-floe-tuning',JSON.stringify({speed:scrollSpeed,delay:offset,window:hitWindow,windowVersion:2}));}catch{}
}
const setOffset=value=>{offset=delayValue(value);syncTuning();};
document.querySelectorAll('[data-tune]').forEach(input=>input.oninput=()=>{if(input.dataset.tune==='speed')scrollSpeed=speedValue(input.value);else if(input.dataset.tune==='delay')offset=delayValue(input.value);else hitWindow=windowValue(input.value);syncTuning();});
document.querySelectorAll('[data-reset-tuning]').forEach(button=>button.onclick=()=>{scrollSpeed=1;offset=0;hitWindow=DEFAULT_WINDOW;syncTuning();});
syncTuning();
const selection=()=>tracks.find(t=>t.id===document.querySelector('[name=song]:checked')?.value)||tracks[0],level=()=>document.querySelector('[name=level]:checked').value;
function preview(){if(!tracks.length)return;game=new FloeRun(selection(),level(),($('practice').checked||$('blind').checked),{delay:offset,window:hitWindow});view.reset(game);pulseHud.reset();view.hideNotes=$('blind').checked;finished=false;$('clock').textContent=fmt(game.track.duration);$('menuSong').textContent=game.track.title+' · '+Math.round(game.track.bpm)+' BPM';$('footerSong').textContent=game.track.title+' · 438 隻魚';$('progress').style.width='0%';$('difficultyNote').textContent=`${game.profile.label} · ${game.notes.length} 拍 · ${game.profile.stride===1?'全拍＋八分連打':`每 ${game.profile.stride} 拍一次`} · ${fmt(game.track.duration)}`;$('start').textContent='開始吸氣 →';$('timingReport').href=game.track.id==='floe-third'?'assets/floe/timing-report-3.json':game.track.id==='floe-second'?'assets/floe/timing-report.json':'assets/pulse/timing-report.json';}
function syncSoundButton(){$('sound').setAttribute('aria-pressed',!!audio&&!muted);$('sound').setAttribute('aria-label',audio?'切換聲音':'開啟聲音');$('sound').textContent=muted?'♪̸':'♫';}
async function prepareAudio(){audio??=new DuetAudio(selection());await audio.ctx.resume();audio.mute(muted);await audio.loadSamples();syncSoundButton();return audio;}
async function getAudio(track=selection()){await prepareAudio();audio.track=track;await audio.load(track);return audio;}
function menuMusic(){if(!audio||muted||document.hidden||audition||game?.status!=='ready'||!$('restScreen').classList.contains('hidden'))return;audio.menu().then(()=>{if(audio.menuVoice&&lastHungerCycle<0)visual=0;}).catch(e=>$('error').textContent=e.message);}

function stopAudition(){if(audition)audio?.pause();audition=false;$('listen').textContent='試聽 16 秒';}
async function start(){
  if(loading||!tracks.length)return;artPreview=null;show('previewControl',false);show('setup',false);loading=true;$('start').disabled=true;$('error').textContent='';stopAudition();audio?.stopMenu();audio?.stopEffects();
  const track=selection(),difficulty=level(),practice=($('practice').checked||$('blind').checked);
  try{await getAudio(track);audio.filter.frequency.value=18000;audio.lastHeart=-100;game=new FloeRun(track,difficulty,practice,{delay:offset,window:hitWindow});game.startBreath();view.reset(game);pulseHud.reset();view.hideNotes=$('blind').checked;breathTime=0;finished=false;audio.sample('start',{volume:.3});for(const id of ['opening','ending','paused','hint','warning','hud','laneButtons'])show(id,false);for(const id of ['breathCaption','tap','pause','hud'])show(id,true);$('tap').firstChild.textContent='連打補氣';previous=performance.now();audio.sample('inhale',{volume:.35,duration:3.8});$('scene').focus();if(document.hidden)pause();}
  catch(e){$('error').textContent='無法載入音樂：'+e.message;}finally{loading=false;$('start').disabled=false;}
}
function press(lane,inputEvent){
  if(artPreview||!$('paused').classList.contains('hidden'))return;
  if(game?.status==='breathing'){game.tapBreath();events();}
  else if(game?.status==='playing'){
    let stamp=inputEvent?.timeStamp??performance.now();if(stamp>1e12)stamp-=performance.timeOrigin;
    const time=Math.max(0,audio.timeAt(stamp));if(!game.breathingActive)view.input(lane,time);game.press(lane,time);events();
  }
}
function events(){for(const e of game.events.splice(0)){if(e.type==='breathTap')audio?.sample('button',{volume:.22,duration:.09});else audio?.event(e,game);if(e.type==='breath'&&!e.big)audio?.sample('inhale',{volume:.35,duration:1.5});view.emit(e,game);pulseHud.event(e,game);if(e.type==='miss'&&e.reason==='late')$('timing').textContent='TOO LATE · 太晚按';if(['won','lost'].includes(e.type))finish();}}
function finish(){if(finished)return;finished=true;if(game.status==='lost')audio.pause();else audio.music.gain.setTargetAtTime(.32,audio.ctx.currentTime,.7);for(const id of ['tap','laneButtons','pause','warning','hint'])show(id,false);show('ending',true);show('judgement',false);
  const messages={friends:['吃飽了，也交到朋友了。','你跨過冰洞、呼喚了同伴。下一次，一起游吧。'],rest:['沒吃飽，先攤一下。','活著走完旅程了。海豹趴在岸上，肚子還想要更多小魚。'],hungryGhost:['還餓著的小幽靈。','沒有累積到 240 隻魚，空空的肚子變成了一隻餓死鬼。'],angel:['有翅膀的小海豹。','已累積至少 240 隻魚，這次化成天使，下一次再回到海裡。']};
  const reason={rhythm:'節奏穩定度歸零。魚靠近時請對準節拍與上下軌，失誤後不能連按補中。',oxygen:'氧氣耗盡。',leap:'錯過了大吸氣前的上岸機會。',route:'沒有完成跨洞、上岸與呼喚。'};
  $('endLabel').textContent=(game.practice?'PRACTICE / ':'')+(game.status==='won'?'旅程完成':'旅程結束');$('endTitle').textContent=messages[game.outcome][0];$('endCopy').textContent=`${reason[game.reason]||''}${messages[game.outcome][1]} 吃到 ${game.food} / 438 隻魚；吃飽目標 360 隻。準確率 ${game.accuracy}%。最高 ${game.maxCombo} COMBO；PERFECT ${game.counts.perfect}／GOOD ${game.counts.good}／MISS ${game.counts.miss}（時機／錯軌 ${game.overpresses} 次）。魚速 ${scrollSpeed.toFixed(1)}×；延遲 ${offset} ms；判定 ±${hitWindow} ms。`;
}
function pause(){if(artPreview||!game||!['playing','breathing'].includes(game.status))return;if(game.status==='playing')audio.pause();audio?.stopEffects();game.pause();show('paused',true);$('pauseTitle').textContent='海會等你。';$('pauseCopy').textContent='氧氣、音樂與旅程都停在這一刻。';$('resume').textContent='繼續旅行 ↗';$('resume').focus();}
function resume(){if(game.status!=='paused'){show('paused',false);$('openTuning').focus();return;}game.resume();previous=performance.now();if(game.status==='playing')audio.resume();show('paused',false);$('scene').focus();}
function back(){artPreview=null;show('previewControl',false);show('setup',false);show('credits',false);show('restScreen',false);audio?.silence();stopAudition();for(const id of ['paused','ending','hud','tap','laneButtons','pause','hint','warning','breathCaption'])show(id,false);show('opening',true);show('judgement',false);preview();lastHungerCycle=-1;menuMusic();}
$('openTuning').onclick=()=>{if(['playing','breathing'].includes(game?.status))pause();else{show('paused',true);$('pauseTitle').textContent='找到舒服的手感。';$('pauseCopy').textContent='設定會自動保存，下次遊玩仍然適用。';$('resume').textContent='完成調整';$('resume').focus();}};
$('start').onclick=start;$('retry').onclick=start;$('back').onclick=back;$('quit').onclick=back;$('pause').onclick=pause;$('resume').onclick=resume;
$('sound').onclick=async()=>{try{if(!audio){await prepareAudio();lastHungerCycle=-1;menuMusic();}else{muted=!muted;audio.mute(muted);if(muted){audio.stopEffects();audio.stopMenu();}else{await audio.ctx.resume();menuMusic();}syncSoundButton();}}catch(e){$('error').textContent=e.message;}};
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('#tap,#upperTap,#lowerTap,#sound'))audio?.sample('button',{volume:.25});},true);
$('tap').onpointerdown=e=>{e.preventDefault();press('lower',e);};$('tap').onclick=e=>{if(e.detail===0)press('lower',e);};
for(const [id,lane] of [['upperTap','upper'],['lowerTap','lower']]){$(id).onpointerdown=e=>{e.preventDefault();press(lane,e);};$(id).onclick=e=>{if(e.detail===0)press(lane,e);};}
document.querySelectorAll('[name=level],#practice,#blind').forEach(e=>e.onchange=()=>{stopAudition();if(e.name==='level'){hitWindow=DEFAULT_WINDOW;syncTuning();}preview();});
addEventListener('keydown',e=>{if(e.code==='Escape'){if(!$('credits').classList.contains('hidden')){$('closeCredits').click();return;}if(!$('restScreen').classList.contains('hidden')){$('closeRest').click();return;}if(!$('paused').classList.contains('hidden')){resume();return;}if(artPreview){back();return;}if(!$('setup').classList.contains('hidden')){closeSetup();return;}game?.status==='paused'?resume():pause();return;}if(!['Space','KeyD','KeyF','KeyJ','KeyK','ArrowUp','ArrowDown'].includes(e.code)||e.repeat||(/INPUT|BUTTON|SUMMARY|SELECT/.test(e.target.tagName)&&!(game?.breathingActive&&game.status!=='paused'||game?.status==='playing'&&!!laneForKey(e.code))))return;e.preventDefault();if(audition){calTap();return;}if(e.code==='Space'&&!game?.breathingActive)return;press(laneForKey(e.code)||'lower',e);});
addEventListener('blur',()=>{pause();stopAudition();audio?.stopMenu();audio?.stopEffects();});addEventListener('focus',menuMusic);document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();stopAudition();audio?.stopMenu();audio?.stopEffects();}else menuMusic();});addEventListener('pagehide',()=>audio?.silence());
$('listen').onclick=async()=>{
  if(audition){stopAudition();return;}if(loading)return;loading=true;$('listen').disabled=true;
  try{await getAudio();samples=[];lastCal=-1;$('applyOffset').disabled=true;clicks=game.notes.filter(n=>n.time>=7&&n.time<23).map(n=>n.time);audio.play(6);for(const t of clicks)audio.clickAt(t);audition=true;$('listen').textContent='停止試聽';$('syncStatus').textContent='聽到清脆輕響時，點「跟拍」；不需要盯著畫面。';}
  catch(e){$('error').textContent=e.message;}finally{loading=false;$('listen').disabled=false;}
};
function calTap(){if(!audition)return;const t=audio.time,i=clicks.reduce((best,n,j)=>Math.abs(n-t)<Math.abs(clicks[best]-t)?j:best,0);if(i===lastCal||Math.abs(clicks[i]-t)>.3)return;lastCal=i;samples.push((t-clicks[i])*1000);const sorted=[...samples].sort((a,b)=>a-b);const median=sorted[Math.floor(sorted.length/2)];$('syncStatus').textContent=`已收集 ${samples.length} 次 · 建議 ${Math.round(median)} ms（包含你的反應時間）`;$('applyOffset').disabled=samples.length<6;}
$('calTap').onclick=calTap;$('applyOffset').onclick=()=>{if(samples.length<6)return;setOffset([...samples].sort((a,b)=>a-b)[Math.floor(samples.length/2)]);stopAudition();$('syncStatus').textContent=`已套用 ${offset} ms，可再次試聽或手動微調。`;};
function closeSetup(){stopAudition();audio?.stopEffects();menuMusic();show('setup',false);$('openSetup').focus();}
const openSetup=()=>{show('setup',true);$('closeSetup').focus();};
$('openSetup').onclick=openSetup;$('menuStart').onclick=openSetup;
$('menuCredits').onclick=()=>{show('credits',true);$('closeCredits').focus();};
$('closeCredits').onclick=()=>{show('credits',false);$('menuCredits').focus();};
$('menuExit').onclick=()=>{audio?.silence();show('restScreen',true);$('closeRest').focus();};
$('closeRest').onclick=()=>{show('restScreen',false);$('menuExit').focus();};
$('home').onclick=()=>{back();$('menuStart').focus();};
document.querySelectorAll('.ice-button').forEach(button=>button.addEventListener('click',()=>{button.classList.add('clicked');setTimeout(()=>button.classList.remove('clicked'),180);}));
$('closeSetup').onclick=closeSetup;
for(const dialogId of ['setup','paused','credits','restScreen'])$(dialogId).addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...$(dialogId).querySelectorAll('button:not(:disabled),input,select,summary,a')].filter(n=>n.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
document.querySelectorAll('[data-preview]').forEach(button=>button.onclick=()=>{
  stopAudition();audio?.silence();preview();artPreview=button.dataset.preview;show('setup',false);
  for(const id of ['opening','breathCaption','hud','hint','warning','ending','tap','laneButtons','pause','judgement'])show(id,false);
  if(artPreview==='start')show('opening',true);
  else if(['breath','breath-full'].includes(artPreview)){game.startBreath();breathTime=artPreview==='breath-full'?2.7:.24;game.air=artPreview==='breath-full'?100:10;game.breathElapsed=breathTime;game.breathTaps=game.air/5;show('breathCaption',true);show('hud',true);}
  else if(artPreview==='dive'){game.status='playing';game.phase='underwater';game.time=19.1;game.air=73;game.food=Number(button.dataset.food)||0;game.stageFood[0]=Math.min(146,game.food);view.motion.growth=view.motion.targetGrowth=game.growth;game.depth=24;game.notes.filter(n=>n.time<19.1).forEach(n=>n.result='hit');game.cursor=game.notes.findIndex(n=>!n.result);show('hud',true);show('hint',true);}
  else{game.status=['friends','rest'].includes(artPreview)?'won':'lost';game.outcome=artPreview;game.food={friends:380,rest:310,hungryGhost:170,angel:260}[artPreview];game.phase='shore';game.leaped=true;game.called=true;show('ending',true);$('endLabel').textContent='ENDING / 畫面預覽';$('endTitle').textContent={friends:'吃飽了，也交到朋友了。',rest:'沒吃飽，先攤一下。',hungryGhost:'還餓著的小幽靈。',angel:'有翅膀的小海豹。'}[artPreview];$('endCopy').textContent='這是結局的美術預覽，實際結局會依旅程與進食結果決定。';}
  show('previewControl',true);$('exitPreview').focus();
});$('exitPreview').onclick=back;
$('previewSound').onclick=async()=>{const button=$('previewSound');button.disabled=true;try{await prepareAudio();if(muted){$('soundStatus').textContent='目前已靜音，請先開啟右上角聲音。';return;}audio.stopMenu();audio.stopEffects();const key=$('soundChoice').value;audio.sample(key,{volume:.45});$('soundStatus').textContent='正在試聽：'+$('soundChoice').selectedOptions[0].textContent;}catch(e){$('soundStatus').textContent=e.message;}finally{button.disabled=false;}};
function resize(){view.resize(document.querySelector('.world').clientWidth,document.querySelector('.world').clientHeight,devicePixelRatio||1);}addEventListener('resize',resize);resize();
const fmt=t=>`${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;
function frame(now){const elapsed=Math.max(0,(now-previous)/1000||0),dt=Math.min(.05,elapsed);previous=now;
  if(game){if(game.status==='breathing'&&!artPreview){game.advanceBreath(elapsed);breathTime=game.breathElapsed;if(game.status==='playing'){audio.stopEffects();audio.play(0);events();}}if(game.status==='ready'&&!document.hidden)visual+=dt;
    if(!artPreview&&audio?.enabled&&!document.hidden){if(game.status==='ready'&&audio.menuVoice){const cycle=hungerPose(visual).cycle;if(cycle!==lastHungerCycle){lastHungerCycle=cycle;audio.sample('hungry',{volume:.6});}}}
    if(!artPreview&&game.status==='playing'){game.update(Math.max(0,audio.time));events();audio.danger(game.danger,game.time);}
    view.draw(game,game.status==='breathing'||game.status==='paused'&&game.beforePause==='breathing'?breathTime:game.status==='ready'?visual:game.time,dt);
    pulseHud.draw(game,dt);const screen=view.flow.current;document.querySelector('.world').dataset.status=game.breathingActive?'breathing':game.status;document.querySelector('.world').dataset.scene=screen;document.querySelector('.world').dataset.outcome=game.outcome||'';document.querySelector('.world').dataset.preview=!!artPreview;
    $('sceneNumber').textContent={start:'01 / 冰川上的小海豹',breath:'02 / 給自己一口氣',dive:'03 / 循著音樂，游向海底',ending:'04 / 旅程的另一端'}[screen];
    const rolling=game.breathingActive;show('breathCaption',rolling);show('tap',rolling&&!artPreview);show('laneButtons',game.status==='playing'&&!rolling&&!artPreview);if(rolling){show('hint',false);show('warning',false);$('breathCaption').querySelector('h2').textContent=`連打吸氣！${game.breathTaps} 下 · 每下 +5%`;const air=Math.round(game.air);$('airValue').textContent=air+'%';$('airFill').style.width=air+'%';$('airMeter').setAttribute('aria-valuenow',air);$('airMeter').classList.toggle('low',false);$('chapter').textContent='準備下海';$('trackTitle').textContent=game.track.title;$('form').textContent='時間到自動下海';}
    if(game.status==='playing'&&!rolling||finished){show('hint',game.status==='playing'&&!artPreview);
      const stage=game.track.stageBounds.findIndex((b,i,a)=>i<a.length-1&&game.time>=b&&game.time<a[i+1]);const s=Math.max(0,Math.min(2,stage<0?game.progress>.9?2:0:stage));
      $('trackTitle').textContent=game.track.title;$('chapter').textContent=view.w<760?`${game.practice?'練習 · ':''}${['晨光','冰廊','歸途'][s]} ${game.stageFood[s]}/146`:`${game.practice?'練習 · ':''}0${s+1} / ${['晨光淺海','藍色冰廊','極光歸途'][s]} · 本段 ${game.stageFood[s]} / 146 隻`;
      $('form').textContent=view.w<760?`體型 ${Math.round(view.motion.growth*100)}% · ${game.depth} m`:`${['小海豹','圓滾滾','飽飽海豹'][game.form]} · 體型 ${Math.round(view.motion.growth*100)}% · ${game.depth} m`;
      $('airValue').textContent=`${Math.ceil(game.air)}%`;$('airFill').style.width=game.air+'%';$('airMeter').setAttribute('aria-valuenow',Math.ceil(game.air));$('airMeter').classList.toggle('low',game.air<35);
      $('foodValue').textContent=`${game.food} / 360`;$('foodFill').style.width=Math.min(100,game.food/360*100)+'%';$('foodMeter').setAttribute('aria-valuenow',Math.min(360,game.food));
      $('progress').style.width=game.progress*100+'%';$('clock').textContent=fmt(game.time)+' / '+fmt(game.track.duration);
      const next=game.target,gate=game.notes.slice(game.cursor).find(n=>!n.result&&n.kind!=='fish');
      $('hint').innerHTML=`<strong>${game.phase==='underwater'?'跟著鼓點，咬住小魚。':game.phase==='surface'?'吸一小口氣，再出發。':game.called?'朋友聽見了，旅程即將完成。':'跟著音樂，準備下一段旅程。'}</strong>${game.phase==='underwater'?`${game.time<game.track.introEnd?'前奏 · 放鬆準備，魚群正在靠近':`${$('blind').checked?'純聽練習 · ':''}冰洞倒數 ${Math.max(0,(gate?game.noteTime(gate):0)-game.time).toFixed(1)} 秒`}`:next?`下一拍 ${next.lane==='upper'?'D / F / ↑ 上排':'J / K / ↓ 下排'}：${{dive:'入水',leap:'大吸氣跨洞',call:'呼喚同伴',exit:'上岸'}[next.kind]||'跟上音樂'}`:''}`;
      show('warning',game.status==='playing'&&game.danger>.05);$('warning').textContent=game.air<10?'最後一口氣！準拍衝向釣魚人的洞口。':game.air<25?'氧氣不足，下一個冰洞一定要抓準。':'呼吸漸急。看好釣魚人，準備上岸。';
    }
    Object.assign($('scene').dataset,{status:game.status,phase:game.phase,time:game.time.toFixed(3),nextNote:game.target?game.noteTime(game.target):'',nextKind:game.target?.kind??'',food:game.food,air:game.air.toFixed(2),outcome:game.outcome||'',breath:game.breathSize(breathTime).toFixed(3),breathTaps:game.breathTaps,breathRemaining:game.breathRemaining.toFixed(3),hungerFrame:view.canvasFrame??0,combo:game.combo,grade:game.feedback?.result||'',score:game.score,accuracy:game.accuracy,audioState:audio?.ctx.state||'locked',menuAudio:!!audio?.menuVoice,effect:audio?.lastCue||'',effectCount:audio?.voices.size||0,decodedDuration:audio?.buffer?.duration||0,stability:game.stability.toFixed(1),overpresses:game.overpresses,speedMultiplier:scrollSpeed,delayMs:offset,windowMs:hitWindow,nextLane:game.target?.lane??''});
  }if(audition){$('listen').dataset.time=audio.time.toFixed(3);$('listen').dataset.nextClick=clicks.find(t=>t>=audio.time-.1)??'';if(audio.time>=22.9)stopAudition();}requestAnimationFrame(frame);
}
try{const res=await fetch('assets/floe/chart.json?v=12.1');if(!res.ok)throw Error('譜面讀取失敗');tracks=(await res.json()).tracks.map((track,i)=>({...track,title:`音樂${i+1}`}));
$('songPicker').innerHTML='<legend>選擇音樂</legend>'+tracks.map((t,i)=>`<label><input type="radio" name="song" value="${t.id}" ${i===0?'checked':''}><span><b>${t.title}</b><small>${Math.round(t.bpm)} BPM · ${fmt(t.duration)}</small></span></label>`).join('');
document.querySelectorAll('[name=song]').forEach(input=>input.onchange=()=>{stopAudition();audio?.silence();if(audio)audio.track=selection();preview();lastHungerCycle=-1;menuMusic();});
await view.ready;preview();const nav=document.querySelector('header nav'),active=nav.querySelector('[aria-current]');nav.scrollLeft=Math.max(0,active.offsetLeft-nav.offsetLeft-(nav.clientWidth-active.clientWidth)/2);$('start').disabled=false;}catch(e){$('error').textContent=e.message;}
requestAnimationFrame(frame);
